platform :ios, '8.0'
inhibit_all_warnings!

target 'ZZFLEXDemo' do

pod 'TLKit', :git => 'https://github.com/tbl00c/TLKit.git', :tag => '0.0.20'

pod 'Masonry', '~> 1.1.0'
pod 'MJRefresh', '~> 3.1.15'

end
