platform :ios, '8.0'
install! 'cocoapods', :generate_multiple_pod_projects => true
use_frameworks!

target 'ZZFLEXDemo' do
pod 'ZZFLEX', :path => '../'

pod 'TLKit', :git => 'https://github.com/tbl00c/TLKit.git'

pod 'Masonry', '~> 1.1.0'
pod 'MJRefresh', '~> 3.1.17'
pod 'XLPhotoBrowser+CoderXL', :git => 'https://github.com/tbl00c/XLPhotoBrowser.git', :tag => '1.2.2'

end
